(defun jason-theme ()
  (interactive)
  (color-theme-install
   '(jason-theme
      ((background-color . "#303030")
      (background-mode . light)
      (border-color . "#404040")
      (cursor-color . "#00f0ed")
      (foreground-color . "#c3c3b7")
      (mouse-color . "black"))
     (fringe ((t (:background "#404040"))))
     (mode-line ((t (:foreground "grey22" :background "OliveDrab3"))))
     (mode-line-inactive ((t (:background "#555555" :background "#222222"))))
     (region ((t (:background "#21577d"))))
     (font-lock-builtin-face ((t (:foreground "#0072eb"))))
     (font-lock-comment-face ((t (:foreground "#c77343"))))
     (font-lock-function-name-face ((t (:foreground "#8cec27"))))
     (font-lock-keyword-face ((t (:foreground "#729fcf"))))
     (font-lock-string-face ((t (:foreground "#e06c6c"))))
     (font-lock-type-face ((t (:foreground"#05ff80"))))
     (font-lock-constant-face ((t (:foreground "#32dcdc"))))
     (font-lock-variable-name-face ((t (:foreground "#3adfc6"))))
     (minibuffer-prompt ((t (:foreground "#60d3e2" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'jason-theme)
